name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    # manual trigger

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container: locietta/loia-dev-base:antlr4

    steps:
    - uses: actions/checkout@v2
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build with CMake
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target all

    - name: Upload compiler binary
      uses: actions/upload-artifact@v3
      with:
        name: tinycc
        path: build/tinycc
